
dist: trusty
sudo: false 

language: python

addons:
  apt:
    packages:
    - python-numpy

python: 
  - "2.7"
  - "3.6"
  
install:
    
    - pip install hdmf==1.6.1
    - pip install pynwb==1.3.0
    - pip install runipy
    - pip install pyabf==2.1.10
    - pip install imageio==2.6.1
script:
    - cd NWB
    - python simple.py
    - python nwb_info.py simple_example.nwb
    
    - python time_series_data.py
    - python nwb_info.py time_series_data.nwb
    
    - python datatypes.py
    - python nwb_info.py datatypes.nwb
    - ls -alt
    
    - cd ../FergusonEtAl2015/
    - runipy TestData.ipynb 
    - ls -alt
    
    - cd ../TriplettEtAl2018
    - runipy TestDataset.ipynb 
    - python ../NWB/nwb_info.py TriplettEtAl2018.nwb
    - ls -alt
    
    # NotImplementedError: unhandled mime type: text/markdown in runipy...
    # - cd ../ScholzEtAl2018
    # - wget https://osf.io/5298q/download -O AML18_moving.hdf5  
    # - wget https://osf.io/sgnrh/download -O AML175_moving.hdf5  
    # - runipy Testing.ipynb 
    # - ls -alt
    
